config/routes.rb
Mlabs::Application.routes.draw do
	
	resources :assignments
	resources :defaults
	resources :directions
	resources :employees do
		member do
			get :jobs
			get :assign
			get :locations
			get :direct
			get :note
			get :notes
		end
	end
	resources :jobs
	resources :locations
	resources :notes
	resources :sessions, only: [:new, :create, :destroy]
	resources :undos do
		member do
			get :reverse
		end
	end
	resources :users

	#assignments
	match 'weekly-assignment' => 'assignments#weekly_assignment', as: 'weekly_assignment'
	match 'wet-assignment' => 'assignments#wet_assignment', as: 'wet_assignment'
	match 'entry-assignment' => 'assignments#entry_assignment', as: 'entry_assignment'
	match 'wones-assignment' => 'assignments#wones_assignment', as: 'wones_assignment'
	match 'rejects-assignment' => 'assignments#rejects_assignment', as: 'rejects_assignment'
	match 'sarah-assignment' => 'assignments#sarah_assignment', as: 'sarah_assignment'
	match 'seat-assignment' => 'assignments#seat_assignment', as: 'seat_assignment'
	match 'delete-assignments' => 'assignments#delete_assignments', as: 'delete_assignments'
	#employees
	match 'sarahs-team' => 'employees#sarah_team', as: 'sarah_team'
	match 'qns-team' => 'employees#qns_team', as: 'qns_team'
	match 'wet-ones' => 'employees#wet_ones', as: 'wet_ones'
	#jobs
	match 'all-jobs' => 'jobs#all_jobs', as: 'all_jobs'
	match 'wet-station' => 'jobs#wet_station', as: 'wet_station'
	match 'entry-station' => 'jobs#entry_station', as: 'entry_station'
	match 'wones-station' => 'jobs#wones_station', as: 'wones_station'
	match 'rejects-station' => 'jobs#rejects_station', as: 'rejects_station'
	match 'sarah-station' => 'jobs#sarah_station', as: 'sarah_station'
	#locations
	match 'switch-locations' => 'locations#switch_locations', as: 'switch_locations'
	match 'set-locations' => 'locations#set_locations', as: 'set_locations'
	match 'delete-directions' => 'locations#delete_directions', as: 'delete_directions'
	#pages
	root to: 'pages#dashboard'
	#sessions
	match 'signin' => 'sessions#new', as: 'signin'
	match 'signout' => 'sessions#destroy', as: 'signout'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	attr_accessible :name, :first_name, :last_name, :tier, :wet_worked, :entry_worked, 
					:vacation, :floater, :wones_team, :wones_worked, :qns_team, :qns_worked, 
					:sarah_team, :sarah_worked, :must_assign, :station, :seat

	has_many :assignments, dependent: :destroy
	has_many :jobs, through: :assignments

	has_many :directions, dependent: :destroy
	has_many :locations, through: :directions

	has_many :notes, dependent: :destroy

	validates :name, presence: true
	validates :name, uniqueness: true
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :tier, presence: true

	default_scope order: "employees.last_name ASC"

	def self.search(search)
		if search
			search = search.to_s
			tier = search.to_i
			if Rails.env.production?
				where("name ILIKE ? OR first_name ILIKE ? OR last_name ILIKE ? OR tier = ?", "%#{search}%", "%#{search}%", "%#{search}%", tier)
			else
				where("name LIKE ? OR first_name LIKE ? OR last_name LIKE ? OR tier = ?", "%#{search}%", "%#{search}%", "%#{search}%", tier)
			end
		else
			scoped
		end
	end

	def current_location
		if self.directions.first
			self.directions.first.location_id
		else
			nil
		end
	end

	def on_team?
		if self.wones_team? || self.qns_team? || self.sarah_team?
			true
		else
			false
		end
	end

	def currently_wet?
		if self.assignments.first
			if self.assignments.first.job_id == 1 && self.assignments.first.created_at.strftime("%m %d %y") == Time.now.strftime("%m %d %y")
				true
			else
				false
			end
		else
			false
		end
	end

	def currently_working?
		if self.assignments.first.nil?
			false
		else
			today = Time.now.strftime("%w").to_i
			if today == 0
				false
			elsif today == 1
				if self.assignments.first.created_at > Time.now - 86400 * 1
					true
				else
					false
				end
			elsif today == 2
				if self.assignments.first.created_at > Time.now - 86400 * 2
					true
				else
					false
				end
			elsif today == 3
				if self.assignments.first.created_at > Time.now - 86400 * 3
					true
				else
					false
				end
			elsif today == 4
				if self.assignments.first.created_at > Time.now - 86400 * 4
					true
				else
					false
				end
			elsif today == 5
				if self.assignments.first.created_at > Time.now - 86400 * 5
					true
				else
					false
				end
			elsif today == 6
				if self.assignments.first.created_at > Time.now - 86400 * 6
					true
				else
					false
				end
			end
		end
	end

	def working?(job)
		if self.assignments.first.nil?
			false
		else
			today = Time.now.strftime("%w").to_i
			if today == 0
				false
			elsif today == 1
				if self.assignments.first.job_id == job && self.assignments.first.created_at > Time.now - 86400 * 1
					true
				else
					false
				end
			elsif today == 2
				if self.assignments.first.job_id == job && self.assignments.first.created_at > Time.now - 86400 * 2
					true
				else
					false
				end
			elsif today == 3
				if self.assignments.first.job_id == job && self.assignments.first.created_at > Time.now - 86400 * 3
					true
				else
					false
				end
			elsif today == 4
				if self.assignments.first.job_id == job && self.assignments.first.created_at > Time.now - 86400 * 4
					true
				else
					false
				end
			elsif today == 5
				if self.assignments.first.job_id == job && self.assignments.first.created_at > Time.now - 86400 * 5
					true
				else
					false
				end
			elsif today == 6
				if self.assignments.first.job_id == job && self.assignments.first.created_at > Time.now - 86400 * 6
					true
				else
					false
				end
			end
		end
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	before_filter :authenticate

	def index
		@title = "All Employees"
		@search = Employee.search(params[:search])
		@employees = @search.paginate(page: params[:page], per_page: 20)
	end

	def new
		@title = "New Employee"
		@employee = Employee.new
	end

	def create
		if params[:employee][:first_name] && params[:employee][:last_name] && params[:employee][:name] == ""
			params[:employee][:name] = "#{params[:employee][:first_name]} #{params[:employee][:last_name]}"
		elsif params[:employee][:name].split(' ').size >= 2 && params[:employee][:first_name] == "" && params[:employee][:last_name] == ""
			params[:employee][:first_name] = "#{params[:employee][:name].split(' ')[0]}"
			params[:employee][:last_name] = "#{params[:employee][:name].split(' ')[1]}"
		end
		@employee = Employee.new(params[:employee])
		if @employee.save
			redirect_to @employee
		else
			render 'new'
		end
	end

	def show
		@employee = Employee.find(params[:id])
		@title = "#{@employee.name}"
		@all_assignments = @employee.assignments
		@assignments = @all_assignments.take(5)
		@all_directions = @employee.directions
		@directions = @all_directions.take(5)
		@all_notes = @employee.notes
		@notes = @all_notes.take(5)
	end

	def edit
		@title = "Edit Employee"
		@employee = Employee.find(params[:id])
	end

	def update
		@employee = Employee.find(params[:id])
		if params[:employee][:first_name] && params[:employee][:last_name] && params[:employee][:name] == ""
			params[:employee][:name] = "#{params[:employee][:first_name]} #{params[:employee][:last_name]}"
		elsif params[:employee][:name].split(' ').size >= 2 && params[:employee][:first_name] == "" && params[:employee][:last_name] == ""
			params[:employee][:first_name] = "#{params[:employee][:name].split(' ')[0]}"
			params[:employee][:last_name] = "#{params[:employee][:name].split(' ')[1]}"
		end
		if @employee.update_attributes(params[:employee])
			redirect_to @employee
		else
			@title = "Edit Employee"
			render 'edit'
		end
	end

	def destroy
		Employee.find(params[:id]).destroy
		redirect_to employees_path
	end

	def jobs
		@employee = Employee.find(params[:id])
		@title = "Job Assignments"
		@assignments = @employee.assignments
	end

	def assign
		@employee = Employee.find(params[:id])
		@title = "New Assignment"
		@assignment = Assignment.new
	end

	def locations
		@employee = Employee.find(params[:id])
		@title = "Locations Worked"
		@directions = @employee.directions
	end

	def direct
		@employee = Employee.find(params[:id])
		@title = "New Direction"
		@direction = Direction.new
	end

	def notes
		@employee = Employee.find(params[:id])
		@title = "All Notes"
		@all_notes = @employee.notes.search(params[:search])
		@notes = @all_notes.paginate(page: params[:page], per_page: 40)
	end
	
	def note
		@employee = Employee.find(params[:id])
		@title = "New Note"
		@note = Note.new
	end

	def sarah_team
		@title = "Sarah's Team"
		@search = Employee.where("sarah_team = ?", true).search(params[:search])
		@employees = @search.paginate(page: params[:page], per_page: 20)
		render 'index'
	end

	def qns_team
		@title = "QNS Team"
		@search = Employee.where("qns_team = ?", true).search(params[:search])
		@employees = @search.paginate(page: params[:page], per_page: 20)
		render 'index'
	end

	def wet_ones
		@title = "Wet Ones"
		@search = Employee.where("wones_team = ?", true).search(params[:search])
		@employees = @search.paginate(page: params[:page], per_page: 20)
		render 'index'
	end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div class="employeeSingle">
	<%= link_to "", employee, class: "employeeLink" %>
	<div class="employeeSingleName">
		<p><%= link_to "#{employee.last_name}, #{employee.first_name}", employee %></p>
	</div>
	<div class="employeeSingleStats">
		<div>
			<p class="employeeSingleLabel">Tier:</p>
			<p class="employeeSingleData"><%= employee.tier %></p>
			<div class="clear"></div>
		</div>
		<div>
			<p class="employeeSingleLabel">Location:</p> 
			<p class="employeeSingleData">
				<% if employee.directions.first.nil? %>
					N/A
				<% else %>
					<%= Location.find(employee.directions.first.location_id).name %>
				<% end %>
			</p>
			<div class="clear"></div>
		</div>
		<div>
			<p class="employeeSingleLabel">Last Job:</p> 
			<p class="employeeSingleData">
				<% if employee.assignments.first.nil? %>
					N/A
				<% else %>
					<%= Job.find(employee.assignments.first.job_id).name %> <span class="grey">|</span> <%= employee.assignments.first.created_at.strftime("%b %m, %y")%>
				<% end %>
			</p>
			<div class="clear"></div>
		</div>
	</div>
</div>

app/views/employees/_employee_assignment.erb
<li class="employeeAssignment">
	<div class="employeeAssignmentInfo">
		<%= Job.find(assignment.job_id).name %> <span class="grey"><%= assignment.created_at.strftime("%a %b %d, %y") %> - <%= assignment.created_at.strftime("%I:%M:%S %P") %></span>
	</div>
	<div class="employeeAssignmentEditDelete">
		<%= link_to "Edit", edit_assignment_path(assignment) %>
		<%= link_to "Delete", assignment, method: :delete, confirm: "Are you sure you want to delete this job assignment?" %>
	</div>
</li>

app/views/employees/_employee_direction.html.erb
<li class="employeeAssignment">
	<div class="employeeAssignmentInfo">
		<%= Location.find(direction.location_id).name %> <span class="grey"><%= direction.created_at.strftime("%a %b %d, %y")%> - <%= direction.created_at.strftime("%I:%M:%S %P") %></span>
	</div>
	<div class="employeeAssignmentEditDelete">
		<%= link_to "Edit", edit_direction_path(direction) %>
		<%= link_to "Delete", direction, method: :delete, confirm: "Are you sure you want to delete this location worked?" %>
	</div>
</li>

app/views/employees/_employee_note.html.erb
<li class="employeeAssignment">
	<div class="employeeAssignmentEditDelete">
		<%= link_to "Edit", edit_note_path(note) %>
		<%= link_to "Delete", note, method: :delete, confirm: "Are you sure you want to delete this note?" %>
	</div>
	<div class="employeeNoteInfo">
		<%= link_to "#{note.name}", note %> <span class="grey"><%= note.updated_at.strftime("%a %b %d, %y")%> - <%= note.updated_at.strftime("%I:%M:%S %P") %></span>
	</div>
	<div class="employeeNoteContent">
		<p><%= to_html(note.content) %></p>
	</div>
	<div class="employeeNoteAuthor">
		<% if User.find_by_id(note.user_id) %>
			<p>Added by <%= User.find_by_id(note.user_id).name %></p>
		<% end %>
	</div>
</li>

app/views/employees/_employee_side_panel.html.erb
<ul>
	<li><p>Control Panel</p></li>
	<li><%= link_to "New Employee", new_employee_path %></li>
	<li><p>Primary Functions</p></li>
	<li><%= link_to "Edit Employee", edit_employee_path(@employee) %></li>
	<li><%= link_to "Add Assignment", assign_employee_path(@employee) %></li>
	<li><%= link_to "Add Work Location", direct_employee_path(@employee) %></li>
	<li><%= link_to "Add Note", note_employee_path(@employee) %></li>
	<li><p>Do Not Touch</p></li>
	<li><%= link_to "Delete Employee", @employee, method: :delete, confirm: "Click cancel now!" %></li>
</ul>

app/views/employees/_side_panel.html.erb
<ul>
	<li><p>Control Panel</p></li>
	<li><%= link_to "New Employee", new_employee_path %></li>
	<li><p>Teams</p></li>
	<li><%= link_to "Sarah's Team", sarah_team_path %></li>
	<li><%= link_to "QNS Team", qns_team_path %></li>
	<li><%= link_to "Wet Ones", wet_ones_path %></li>
</ul>

app/views/employees/direct.html.erb
<div class="employeeNew">
	<p class="employeeNewHeader">New Work Direction</p>
	<div class="employeeNewForm">
		<%= form_for @direction do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<div class="field">
				<p>Employee ID</p>
				<%= f.text_field :employee_id, value: "#{@employee.id}", readonly: "readonly" %>
			</div>
			<div class="field">
				<p>Location ID</p>
				<%= f.text_field :location_id, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>Date Worked</p>
				<%= f.datetime_select :created_at, ampm: true, datetime_separator: "", use_short_month: true, order: [:month, :day, :year] %>
			</div>
			<div class="action">
				<%= f.submit "Save" %>
				<%= link_to "Cancel", locations_employee_path(@employee) %>
			</div>
		<% end %>
	</div>
</div>

app/views/employees/edit.html.erb
<div class="employeeNew">
	<p class="employeeNewHeader">Edit Employee</p>
	<%= form_for @employee do |f| %>
		<div class="employeeNewForm">
			<%= render 'shared/error_messages', object: f.object %>
			<div class="field">
				<p>Full Name</p>
				<%= f.text_field :name, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>Employee Tier Level</p>
				<%= f.text_field :tier, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>First Name</p>
				<%= f.text_field :first_name, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>Last Name</p>
				<%= f.text_field :last_name, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>Wet Team</p>
				<%= f.check_box :wones_team %>
			</div>
			<div class="field">
				<p>QNS Team</p>
				<%= f.check_box :qns_team %>
			</div>
			<div class="field">
				<p>Sarah's Team</p>
				<%= f.check_box :sarah_team %>
			</div>
			<div class="field">
				<p>Floater</p>
				<%= f.check_box :floater %>
			</div>
			<div class="action">
				<%= f.submit "Save" %>
				<%= link_to "Cancel", @employee %>
			</div>
		</div>
		<div class="employeeNewForm">
			<div class="field">
				<p>Station Number</p>
				<%= f.text_field :station, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>Seat Number</p>
				<%= f.text_field :seat, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>Must Assign</p>
				<%= f.text_field :must_assign, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>On vacation?</p>
				<%= f.check_box :vacation %>
			</div>
			<div class="field">
				<p>Worked wet station?</p>
				<%= f.check_box :wet_worked %>
			</div>
			<div class="field">
				<p>Worked entry station?</p>
				<%= f.check_box :entry_worked %>
			</div>
			<div class="field">
				<p>Worked wet ones station?</p>
				<%= f.check_box :wones_worked %>
			</div>
			<div class="field">
				<p>Worked rejects station?</p>
				<%= f.check_box :qns_worked %>
			</div>
			<div class="field">
				<p>Worked Sarah's station?</p>
				<%= f.check_box :sarah_worked %>
			</div>
		</div>
	<% end %>
	<div class="clear"></div>
</div>

app/views/employees/index.html.erb
<div class="pageHeader">
	<%= render 'side_panel' %>
</div>
<%= render 'shared/search' %>
<div class="pageContent">
	<p class="employeesHeader">Employees: <%= @search.size %></p>
	<div class="allEmployees">
		<%= render @employees %>
		<%= will_paginate @employees, separator: "" %>
	</div>
	<div class="clear"></div>
</div>

app/views/employees/jobs.html.erb
<div class="pageHeader">
	<%= render 'employee_side_panel' %>
</div>
</div>
<div class="pageContent">
	<div class="employeeShow">
		<p class="employeeShowName"><%= link_to "#{@employee.name}", @employee %></p>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Job Assignments: <%= @assignments.size %></p>
			<ol>
				<%= render partial: 'employee_assignment', collection: @assignments, as: :assignment %>
			</ol>
		</div>
	</div>
</div>

app/views/employees/locations.html.erb
<div class="pageHeader">
	<%= render 'employee_side_panel' %>
</div>
</div>
<div class="pageContent">
	<div class="employeeShow">
		<p class="employeeShowName"><%= link_to "#{@employee.name}", @employee %></p>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Locations Worked: <%= @directions.size %></p>
			<ol>
				<%= render partial: 'employee_direction', collection: @directions, as: :direction %>
			</ol>
		</div>
	</div>
</div>

app/views/employees/note.html.erb
<div class="employeeNew">
	<p class="employeeNewHeader">New Note</p>
	<%= form_for @note do |f| %>
		<div class="employeeNewForm">
			<%= render 'shared/error_messages', object: f.object %>
			<%= f.hidden_field :employee_id, value: @employee.id %>
			<div class="field">
				<p>Note Name</p>
				<%= f.text_field :name, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>Content</p>
				<%= f.text_area :content, autocomplete: "off", class: "noteContent" %>
			</div>
			<div class="action">
				<%= f.submit "Create" %>
				<%= link_to "Cancel", notes_employee_path(@employee) %>
			</div>
		</div>
	<% end %>
	<div class="clear"></div>
</div>

app/views/employees/notes.html.erb
<div class="pageHeader">
	<%= render 'employee_side_panel' %>
</div>
<%= render 'shared/search' %>
<div class="pageContent">
	<div class="employeeShow">
		<p class="employeeShowName"><%= link_to "#{@employee.name}", @employee %></p>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Employee Notes: <%= @all_notes.size %></p>
			<ol>
				<%= render partial: 'employee_note', collection: @notes, as: :note %>
			</ol>
			<%= will_paginate @notes, separator: "" %>
		</div>
	</div>
</div>

app/views/employees/show.html.erb
<div class="pageHeader">
	<%= render 'employee_side_panel' %>
</div>
</div>
<div class="pageContent">
	<div class="employeeShow">
		<p class="employeeShowName"><%= link_to "#{@employee.name}", @employee %></p>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Tier Level</p>
			<p><%= @employee.tier %></p>
		</div>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Team</p>
			<% if @employee.wones_team? || @employee.qns_team? || @employee.sarah_team? %>
				<% if @employee.wones_team? %>
					<p>Wet Ones</p>
				<% end %>
				<% if @employee.qns_team? %>
					<p>QNS</p>
				<% end %>
				<% if @employee.sarah_team? %>
					<p>Sarah's</p>
				<% end %>
			<% else %>
				<p>None</p>
			<% end %>
		</div>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Floater</p>
			<p>
				<% if @employee.floater? %>
					Yes
				<% else %>
					No
				<% end %>
			</p>
		</div>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Vacation</p>
			<p>
				<% if @employee.vacation? %>
					Yes
				<% else %>
					No
				<% end %>
			</p>
		</div>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Worked Stations</p>
			<% if @employee.wet_worked? || @employee.entry_worked? || @employee.wones_worked? || @employee.qns_worked? || @employee.sarah_worked? %>
				<% if @employee.wet_worked? %>
					<p>Wet Station</p>
				<% end %>
				<% if @employee.entry_worked? %>
					<p>Entry Station</p>
				<% end %>
				<% if @employee.wones_worked? %>
					<p>Wet Ones</p>
				<% end %>
				<% if @employee.qns_worked? %>
					<p>Reject's Station</p>
				<% end %>
				<% if @employee.sarah_worked? %>
					<p>Sarah's Station</p>
				<% end %>
			<% else %>
				<p>None</p>
			<% end %>
		</div>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Seating Position</p>
			<p>Station: <%= @employee.station %></p>
			<p>Seat: <%= @employee.seat %></p>
		</div>
		<% if @employee.must_assign != 0 %>
			<div class="employeeShowSection">
				<p class="employeeShowSectionHeader">Must Assign</p>
				<p><%= @employee.must_assign %></p>
			</div>
		<% end %>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Job Assignments: <%= @all_assignments.size %> <%= link_to "See All", jobs_employee_path(@employee) %></p>
			<ol>
				<%= render partial: 'employee_assignment', collection: @assignments, as: :assignment %>
			</ol>
		</div>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Locations Worked: <%= @all_directions.size %> <%= link_to "See All", locations_employee_path(@employee) %></p>
			<ol>
				<%= render partial: 'employee_direction', collection: @directions, as: :direction %>
			</ol>
		</div>
		<div class="employeeShowSection">
			<p class="employeeShowSectionHeader">Employee Notes: <%= @notes.size %> <%= link_to "See All", notes_employee_path(@employee) %></p>
			<ol>
				<% @notes.each do |note| %>
					<li class="employeeAssignment">
						<div class="employeeAssignmentInfo">
							<%= link_to "#{note.name}", note %> <span class="grey"><%= note.updated_at.strftime("%a %b %d, %y")%> - <%= note.updated_at.strftime("%I:%M:%S %P") %></span>
						</div>
						<div class="employeeAssignmentEditDelete">
							<%= link_to "Edit", edit_note_path(note) %>
							<%= link_to "Delete", note, method: :delete, confirm: "Are you sure you want to delete this note?" %>
						</div>
					</li>
				<% end %>
			</ol>
		</div>
	</div>
</div>