config/routes.rb
Mlabs::Application.routes.draw do
	
	resources :assignments
	resources :defaults
	resources :directions
	resources :employees do
		member do
			get :jobs
			get :assign
			get :locations
			get :direct
			get :note
			get :notes
		end
	end
	resources :jobs
	resources :locations
	resources :notes
	resources :sessions, only: [:new, :create, :destroy]
	resources :undos do
		member do
			get :reverse
		end
	end
	resources :users

	#assignments
	match 'weekly-assignment' => 'assignments#weekly_assignment', as: 'weekly_assignment'
	match 'wet-assignment' => 'assignments#wet_assignment', as: 'wet_assignment'
	match 'entry-assignment' => 'assignments#entry_assignment', as: 'entry_assignment'
	match 'wones-assignment' => 'assignments#wones_assignment', as: 'wones_assignment'
	match 'rejects-assignment' => 'assignments#rejects_assignment', as: 'rejects_assignment'
	match 'sarah-assignment' => 'assignments#sarah_assignment', as: 'sarah_assignment'
	match 'seat-assignment' => 'assignments#seat_assignment', as: 'seat_assignment'
	match 'delete-assignments' => 'assignments#delete_assignments', as: 'delete_assignments'
	#employees
	match 'sarahs-team' => 'employees#sarah_team', as: 'sarah_team'
	match 'qns-team' => 'employees#qns_team', as: 'qns_team'
	match 'wet-ones' => 'employees#wet_ones', as: 'wet_ones'
	#jobs
	match 'all-jobs' => 'jobs#all_jobs', as: 'all_jobs'
	match 'wet-station' => 'jobs#wet_station', as: 'wet_station'
	match 'entry-station' => 'jobs#entry_station', as: 'entry_station'
	match 'wones-station' => 'jobs#wones_station', as: 'wones_station'
	match 'rejects-station' => 'jobs#rejects_station', as: 'rejects_station'
	match 'sarah-station' => 'jobs#sarah_station', as: 'sarah_station'
	#locations
	match 'switch-locations' => 'locations#switch_locations', as: 'switch_locations'
	match 'set-locations' => 'locations#set_locations', as: 'set_locations'
	match 'delete-directions' => 'locations#delete_directions', as: 'delete_directions'
	#pages
	root to: 'pages#dashboard'
	#sessions
	match 'signin' => 'sessions#new', as: 'signin'
	match 'signout' => 'sessions#destroy', as: 'signout'
end

app/models/job.rb
class Job < ActiveRecord::Base
	attr_accessible :id, :name

	has_many :assignments, dependent: :destroy
	has_many :employees, through: :assignments

	validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_filter :default_settings, only: :index
	before_filter :authenticate
	before_filter :admin_user, only: [:new, :create, :show, :edit, :update, :destroy, :all_jobs]

	def index
		@title = "Job Assignments"
		@wet = Assignment.where("job_id = ?", 1).take(@wet_needed * @work_days)
		@wet_station = @wet.group_by(&:month_day)
		@entry = Assignment.where("job_id = ?", 2).take(@entry_needed)
		@entry_station = @entry.group_by(&:month_day)
		@wones = Assignment.where("job_id = ?", 3).take(@wones_needed)
		@wones_station = @wones.group_by(&:month_day)
		@qns = Assignment.where("job_id = ?", 4).take(@qns_needed)
		@qns_station = @qns.group_by(&:month_day)
		@sarah = Assignment.where("job_id = ?", 5).take(@sarah_needed)
		@sarah_station = @sarah.group_by(&:month_day)
	end

	def new
		@title = "New Job"
		@job = Job.new
	end

	def create
		@job = Job.new(params[:job])
		if @job.save
			redirect_to all_jobs_path
		else
			render 'new'
		end
	end

	def show
		@job = Job.find(params[:id])
		@title = "#{@job.name}"
	end

	def edit
		@title = "Edit Job"
		@job = Job.find(params[:id])
	end

	def update
		@job = Job.find(params[:id])
		if @job.update_attributes(params[:job])
			redirect_to all_jobs_path
		else
			@title = "Edit Job"
			render 'edit'
		end
	end

	def destroy
		Job.find(params[:id]).destroy
		redirect_to all_jobs_path
	end

	def all_jobs
		@title = "All Jobs"
		@jobs = Job.all
	end

	def wet_station
		@title = "Wet Station"
		@all_assignments = Assignment.where("job_id = ?", 1).search(params[:search])
		@assignments = @all_assignments.paginate(page: params[:page], per_page: 20)
		render 'jobs'
	end

	def entry_station
		@title = "Entry Station"
		@all_assignments = Assignment.where("job_id = ?", 2).search(params[:search])
		@assignments = @all_assignments.paginate(page: params[:page], per_page: 20)
		render 'jobs'
	end

	def wones_station
		@title = "Wet Ones Station"
		@all_assignments = Assignment.where("job_id = ?", 3).search(params[:search])
		@assignments = @all_assignments.paginate(page: params[:page], per_page: 20)
		render 'jobs'
	end

	def rejects_station
		@title = "Rejects Station"
		@all_assignments = Assignment.where("job_id = ?", 4).search(params[:search])
		@assignments = @all_assignments.paginate(page: params[:page], per_page: 20)
		render 'jobs'
	end

	def sarah_station
		@title = "Sarah's Station"
		@all_assignments = Assignment.where("job_id = ?", 5).search(params[:search])
		@assignments = @all_assignments.paginate(page: params[:page], per_page: 20)
		render 'jobs'
	end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_assignment.html.erb
<div class="singleJob">
	<%= link_to "", Employee.find(assignment.employee_id), class: "singleJobEmployeeLink" %>
	<div class="singleJobEmployee">
		<p><%= link_to "#{Employee.find(assignment.employee_id).name}", Employee.find(assignment.employee_id) %></p>
	</div>
	<div class="singleJobInfo">
		<div class="singleJobTimes">
			<p>Job Worked: <%= pluralize(Employee.find(assignment.employee_id).assignments.where("job_id = ? AND created_at <= ?", assignment.job_id, assignment.created_at).size, 'time') %></p>
		</div>
		<div class="singleJobCreated">
			<p><%= assignment.created_at.strftime("%a %b %d, %y")%> - <%= assignment.created_at.strftime("%I:%M:%S %P") %></p>
		</div>
	</div>
</div>

app/views/jobs/_employee_job.html.erb
<div class="employeeJob">
	<%= link_to "#{Employee.find(assignment.employee_id).name}", Employee.find(assignment.employee_id) %>
</div>

app/views/jobs/_side_panel.html.erb
<ul>
	<li><p>Primary Functions</p></li>
	<li><%= link_to "Weekly Assignment", weekly_assignment_path %></li>
	<li><%= link_to "Wet Station", wet_assignment_path %></li>
	<li><%= link_to "Seat Assignment", seat_assignment_path, confirm: "Have you assigned all jobs?" %></li>
	<li><p>Manually Assign</p></li>
	<li><%= link_to "Sarah's Station", sarah_assignment_path %></li>
	<li><%= link_to "Rejects Station", rejects_assignment_path %></li>
	<li><%= link_to "Wet Ones", wones_assignment_path %></li>
	<li><%= link_to "Entry Station", entry_assignment_path %></li>
	<% if current_user.admin? %>
		<li><p>Do Not Touch</p></li>
		<li><%= link_to "New Job", new_job_path %></li>
		<li><%= link_to "All Jobs", all_jobs_path %></li>
		<li><%= link_to "Delete All Assignments", delete_assignments_path, confirm: "Click cancel now!" %></li>
	<% end %>
</ul>

app/views/jobs/all_jobs.html.erb
<div class="pageHeader">
	<%= render 'side_panel' %>
</div>
<div class="pageContent">
	<% @jobs.each do |job| %>
		<p><%= job.name %> <%= link_to "Edit", edit_job_path(job) %> | <%= link_to "Delete", job, method: :delete, confirm: "Are you sure you want to delete this job?" %></p>
	<% end %>
</div>

app/views/jobs/edit.html.erb
<div class="employeeNew">
	<p class="employeeNewHeader">Edit Job</p>
	<div class="employeeNewForm">
		<%= form_for @job do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<div class="field">
				<p>Job Name</p>
				<%= f.text_field :name, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>ID</p>
				<%= f.text_field :id, autocomplete: "off" %>
			</div>
			<div class="action">
				<%= f.submit "Save" %>
				<%= link_to "Cancel", all_jobs_path %>
			</div>
		<% end %>
	</div>
	<div class="clear"></div>
</div>

app/views/jobs/index.html.erb
<div class="pageHeader">
	<%= render 'side_panel' %>
</div>
<div class="pageContent">
	<div class="jobs">
		<div class="jobStation wetStation">
			<p class="jobsHeader"><%= link_to "Wet Station", wet_station_path %></p>
			<% @wet_station.each do |month_day, assignments| %>
				<p class="jobsDate"><%= month_day %></p>
				<% for assignment in assignments %>
					<%= render partial: 'employee_job', object: assignment, as: :assignment %>
				<% end %>
			<% end %>
		</div>
		<div class="jobStation entryStation">
			<p class="jobsHeader"><%= link_to "Entry Station", entry_station_path %></p>
			<% @entry_station.each do |month_day, assignments| %>
				<p class="jobsDate"><%= month_day %></p>
				<% for assignment in assignments %>
					<%= render partial: 'employee_job', object: assignment, as: :assignment %>
				<% end %>
			<% end %>
		</div>
		<div class="jobStation wonesStation">
			<p class="jobsHeader"><%= link_to "Wet Ones", wones_station_path %></p>
			<% @wones_station.each do |month_day, assignments| %>
				<p class="jobsDate"><%= month_day %></p>
				<% for assignment in assignments %>
					<%= render partial: 'employee_job', object: assignment, as: :assignment %>
				<% end %>
			<% end %>
		</div>
		<div class="jobStation qnsStation">
			<p class="jobsHeader"><%= link_to "Rejects Station", rejects_station_path %></p>
			<% @qns_station.each do |month_day, assignments| %>
				<p class="jobsDate"><%= month_day %></p>
				<% for assignment in assignments %>
					<%= render partial: 'employee_job', object: assignment, as: :assignment %>
				<% end %>
			<% end %>
		</div>
		<div class="jobStation sarahStation">
			<p class="jobsHeader"><%= link_to "Sarah's Station", sarah_station_path %></p>
			<% @sarah_station.each do |month_day, assignments| %>
				<p class="jobsDate"><%= month_day %></p>
				<% for assignment in assignments %>
					<%= render partial: 'employee_job', object: assignment, as: :assignment %>
				<% end %>
			<% end %>
		</div>
		<div class="clear"></div>
	</div>
</div>

app/views/jobs/jobs.html.erb
<div class="pageHeader">
	<%= render 'side_panel' %>
</div>
<%= render 'shared/search' %>
<div class="pageContent">
	<div class="singleJobHeader">
		<p><%= @title %>: <%= @all_assignments.size %></p>
	</div>
	<div class="singleJobsList">
		<%= render partial: "jobs/assignment", collection: @assignments %>
		<%= will_paginate @assignments, separator: "" %>
	</div>
</div>

app/views/jobs/new.html.erb
<div class="employeeNew">
	<p class="employeeNewHeader">New Job</p>
	<div class="employeeNewForm">
		<%= form_for @job do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<div class="field">
				<p>Job Name</p>
				<%= f.text_field :name, autocomplete: "off" %>
			</div>
			<div class="field">
				<p>ID</p>
				<%= f.text_field :id, autocomplete: "off" %>
			</div>
			<div class="action">
				<%= f.submit "Create" %>
				<%= link_to "Cancel", all_jobs_path %>
			</div>
		<% end %>
	</div>
</div>

app/views/jobs/show.html.erb
<p><%= @job.name %></p>
<p><%= @job.id %></p>