config/routes.rb
Mlabs::Application.routes.draw do
	
	resources :assignments
	resources :defaults
	resources :directions
	resources :employees do
		member do
			get :jobs
			get :assign
			get :locations
			get :direct
			get :note
			get :notes
		end
	end
	resources :jobs
	resources :locations
	resources :notes
	resources :sessions, only: [:new, :create, :destroy]
	resources :undos do
		member do
			get :reverse
		end
	end
	resources :users

	#assignments
	match 'weekly-assignment' => 'assignments#weekly_assignment', as: 'weekly_assignment'
	match 'wet-assignment' => 'assignments#wet_assignment', as: 'wet_assignment'
	match 'entry-assignment' => 'assignments#entry_assignment', as: 'entry_assignment'
	match 'wones-assignment' => 'assignments#wones_assignment', as: 'wones_assignment'
	match 'rejects-assignment' => 'assignments#rejects_assignment', as: 'rejects_assignment'
	match 'sarah-assignment' => 'assignments#sarah_assignment', as: 'sarah_assignment'
	match 'seat-assignment' => 'assignments#seat_assignment', as: 'seat_assignment'
	match 'delete-assignments' => 'assignments#delete_assignments', as: 'delete_assignments'
	#employees
	match 'sarahs-team' => 'employees#sarah_team', as: 'sarah_team'
	match 'qns-team' => 'employees#qns_team', as: 'qns_team'
	match 'wet-ones' => 'employees#wet_ones', as: 'wet_ones'
	#jobs
	match 'all-jobs' => 'jobs#all_jobs', as: 'all_jobs'
	match 'wet-station' => 'jobs#wet_station', as: 'wet_station'
	match 'entry-station' => 'jobs#entry_station', as: 'entry_station'
	match 'wones-station' => 'jobs#wones_station', as: 'wones_station'
	match 'rejects-station' => 'jobs#rejects_station', as: 'rejects_station'
	match 'sarah-station' => 'jobs#sarah_station', as: 'sarah_station'
	#locations
	match 'switch-locations' => 'locations#switch_locations', as: 'switch_locations'
	match 'set-locations' => 'locations#set_locations', as: 'set_locations'
	match 'delete-directions' => 'locations#delete_directions', as: 'delete_directions'
	#pages
	root to: 'pages#dashboard'
	#sessions
	match 'signin' => 'sessions#new', as: 'signin'
	match 'signout' => 'sessions#destroy', as: 'signout'
end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :name

	has_many :directions, dependent: :destroy
	has_many :employees, through: :directions

	validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_filter :authenticate
	before_filter :admin_user, except: [:index, :switch_locations]
	
	def index
		@title = "Work Locations"
		lab_employees = []
		office_employees =[]
		Employee.find_each do |e|
			if e.current_location == 1
				lab_employees.push(e)
			elsif e.current_location == 2
				office_employees.push(e)
			end
		end
		@lab = lab_employees.sort_by { |e| e.last_name }
		@office = office_employees.sort_by { |e| e.last_name }
	end

	def switch_locations
		switch
		redirect_to locations_path
	end

	def new
		@title = "New Location"
		@location = Location.new
	end

	def create
		@location = Location.new(params[:location])
		if @location.save
			redirect_to locations_path
		else
			@title = "New Location"
			render 'new'
		end
	end

	def set_locations
		set
		redirect_to locations_path
	end

	def delete_directions
		Direction.destroy_all
		Undo.where("name = ? OR name = ?", "Set Locations", "Switch Locations").destroy_all
		redirect_to locations_path
	end
end

app/helpers/locations_helper.rb
module LocationsHelper

	def set
		if Default.first
			lab_count = Default.first.lab_employees
			entry_needed = Default.first.entry_employees
			wones_needed = Default.first.wones_employees
			qns_needed = Default.first.qns_employees
			sarah_needed = Default.first.sarah_employees
			wet_needed = Default.first.wet_employees * Default.first.work_days
		else
			lab_count = 24
			entry_needed = 2
			wones_needed = 3
			qns_needed = 1
			sarah_needed = 2
			wet_needed = 10
		end # default values for how many employees of each type are required in the lab and office
		all = Employee.where("vacation = ?", false) 
		if all.size >= lab_count
			limit = ((all.map { |e| e.tier }.sum) * ((lab_count * 1.0)/all.size).round(2)).round
			lab_sum = 0
			while lab_sum < limit - (limit * 0.04).round || lab_sum > limit
				wet_not_worked = 0
				until wet_not_worked >= wet_needed
					entry_not_worked = 0
					if all.select { |e| !e.entry_worked? && !e.on_team? }.size - entry_needed <= entry_needed
						entry_not_worked_max = entry_needed
					else
						entry_not_worked_max = all.select { |e| !e.entry_worked? && !e.on_team? }.size - entry_needed
					end
					until entry_not_worked >= entry_needed && entry_not_worked <= entry_not_worked_max
						wones_not_worked = 0
						if all.select { |e| e.wones_team? && !e.wones_worked? }.size - wones_needed <= wones_needed
							wones_not_worked_max = wones_needed
						else
							wones_not_worked_max = all.select { |e| e.wones_team? && !e.wones_worked? }.size - wones_needed
						end
						until wones_not_worked >= wones_needed && wones_not_worked <= wones_not_worked_max
							qns_not_worked = 0
							if all.select { |e| e.qns_team? && !e.qns_worked? }.size - qns_needed <= qns_needed
								qns_not_worked_max = qns_needed
							else
								qns_not_worked_max = all.select { |e| e.qns_team? && !e.qns_worked? }.size - qns_needed
							end
							until qns_not_worked >= qns_needed && qns_not_worked <= qns_not_worked_max
								sarah_not_worked = 0
								until sarah_not_worked == sarah_needed
									all = all.shuffle
									lab_employees = all[0..(lab_count - 1)]
									office_employees = all[lab_count..(all.size - 1)]
									this_group = lab_employees.select { |e| e.sarah_team? && !e.sarah_worked? }
									sarah_not_worked = this_group.size
									temp_lab = lab_employees - this_group
								end
								this_group = temp_lab.select { |e| e.qns_team? && !e.qns_worked? }
								qns_not_worked = this_group.size
								temp_lab = temp_lab - this_group
								if all.select { |e| e.qns_team? && !e.qns_worked? }.size - qns_needed <= qns_needed
									qns_not_worked_max = qns_needed
								else
									qns_not_worked_max = all.select { |e| e.qns_team? && !e.qns_worked? }.size - qns_needed
								end
							end
							this_group = temp_lab.select { |e| e.wones_team? && !e.wones_worked? }
							wones_not_worked = this_group.size
							temp_lab = temp_lab - this_group
							if all.select { |e| e.wones_team? && !e.wones_worked? }.size - wones_needed <= wones_needed
								wones_not_worked_max = wones_needed
							else
								wones_not_worked_max = all.select { |e| e.wones_team? && !e.wones_worked? }.size - wones_needed
							end
						end
						this_group = temp_lab.select { |e| !e.entry_worked? }
						entry_not_worked = this_group.size
						if all.select { |e| !e.entry_worked? && !e.on_team? }.size - entry_needed <= entry_needed
							entry_not_worked_max = entry_needed
						else
							entry_not_worked_max = all.select { |e| !e.entry_worked? && !e.on_team? }.size - entry_needed
						end
					end
					wet_not_worked = office_employees.select { |e| !e.wet_worked? && !e.sarah_team? }.size
				end
				lab_sum = lab_employees.map { |e| e.tier }.sum
			end
			lab_employees.each do |e|
				e.directions.create(location_id: 1)
			end
			office_employees.each do |e|
				e.directions.create(location_id: 2)
			end
		end
		Undo.create(name: "Set Locations")
	end

	def switch
		if Default.first
			lab_count = Default.first.lab_employees
			entry_needed = Default.first.entry_employees
			wones_needed = Default.first.wones_employees
			qns_needed = Default.first.qns_employees
			sarah_needed = Default.first.sarah_employees
			wet_needed = Default.first.wet_employees * Default.first.work_days
		else
			lab_count = 24
			entry_needed = 2
			wones_needed = 3
			qns_needed = 1
			sarah_needed = 2
			wet_needed = 10
		end # default values for how many employees of each type are required in the lab and office
		lab_employees = []
		office_employees =[]
		Employee.find_each do |e|
			if e.directions.first
				if e.directions.first.location_id == 1
					lab_employees.push(e)
				elsif e.directions.first.location_id == 2
					office_employees.push(e)
				end
			end
		end # put employees that are in the lab into lab_employees and put employees that are in the office into office_employees
		all = lab_employees + office_employees
		tier_sum = all.map{ |e| e.tier }.sum
		limit = (tier_sum * ((lab_employees.size * 1.0)/all.size).round(2)).round # calculate the tier sum value needed to be balanced in the lab
		must_assign_employees = []
		must_assign_wet = []
		undo_sarah = false
		undo_qns = false
		undo_wones = false
		undo_entry = false
		undo_wet = false
		if all.size >= (lab_count * 2.2).round && all.size >= (entry_needed + wones_needed + qns_needed + sarah_needed + wet_needed) * 2
			lab_sum = 0 # make sure the sum of each employee's tier levels are balanced in the lab and office
			while lab_sum < limit - (limit * 0.04).round || lab_sum > limit
				wet_not_worked = 0
				until wet_not_worked >= wet_needed
					entry_not_worked = 0
					if all.select { |e| !e.on_team? && !e.entry_worked? }.size - entry_needed <= entry_needed
						entry_not_worked_max = entry_needed
					else
						entry_not_worked_max = all.select { |e| !e.on_team? && !e.entry_worked? }.size - entry_needed
					end
					until entry_not_worked >= entry_needed && entry_not_worked <= entry_not_worked_max
						wones_not_worked = 0
						if all.select { |e| e.wones_team? && !e.wones_worked? }.size - wones_needed <= wones_needed
							wones_not_worked_max = wones_needed
						else
							wones_not_worked_max = all.select { |e| e.wones_team? && !e.wones_worked? }.size - wones_needed
						end
						until wones_not_worked >= wones_needed && wones_not_worked <= wones_not_worked_max
							qns_not_worked = 0 # make sure there is at least 1 employee on the QNS Team that has not worked at Rejects Station
							if all.select { |e| e.qns_team? && !e.qns_worked? }.size - qns_needed <= qns_needed
								qns_not_worked_max = qns_needed
							else
								qns_not_worked_max = all.select { |e| e.qns_team? && !e.qns_worked? }.size - qns_needed
							end
							until qns_not_worked >= qns_needed && qns_not_worked <= qns_not_worked_max
								sarah_not_worked = 0 # make sure there are exactly 2 employees on Sarah's Team that has not worked at Sarah's Station
								until sarah_not_worked == sarah_needed
									if all.select { |e| e.sarah_team? && !e.sarah_worked? }.size < sarah_needed
										sarahs_team = all.select { |e| e.sarah_team? } # all employees on Sarah's Team
										sarahs_team_not_worked = sarahs_team.select { |e| !e.sarah_worked? } # all employees on Sarah's Team that have not worked Sarah's Station
										sarahs_team_not_worked.each do |e|
											e.update_attribute(:must_assign, 5)
											must_assign_employees.push(e)
										end
										sarahs_team.each do |e|
											e.update_attribute(:sarah_worked, false)
										end
										undo_sarah = true
									end
									if all.select { |e| e.qns_team? && !e.qns_worked? }.size < qns_needed
										qns_team = all.select { |e| e.qns_team? } # all employees on QNS Team
										qns_team_not_worked = qns_team.select { |e| !e.qns_worked? } # all employees on QNS Team that have not worked QNS Station
										qns_team_not_worked.each do |e|
											e.update_attribute(:must_assign, 4)
											must_assign_employees.push(e)
										end
										qns_team.each do |e|
											e.update_attribute(:qns_worked, false)
										end
										undo_qns = true
									end
									if all.select { |e| e.wones_team? && !e.wones_worked? }.size < wones_needed
										wones_team = all.select { |e| e.wones_team? } # all employees on Wet Ones Team
										wones_team_not_worked = wones_team.select { |e| !e.wones_worked? } # all employees on Wet Ones Team that have not worked Wet Ones Station
										wones_team_not_worked.each do |e|
											e.update_attribute(:must_assign, 3)
											must_assign_employees.push(e)
										end
										wones_team.each do |e|
											e.update_attribute(:wones_worked, false)
										end
										undo_wones = true
									end
									if all.select { |e| !e.on_team? && !e.entry_worked? }.size < entry_needed
										entry_team = all.select { |e| !e.on_team? } # all employees not on a team
										entry_team_not_worked = entry_team.select { |e| !e.entry_worked? } # all employees not on a team that have not worked Entry Station
										entry_team_not_worked.each do |e|
											e.update_attribute(:must_assign, 2)
											must_assign_employees.push(e)
										end
										entry_team.each do |e|
											e.update_attribute(:entry_worked, false)
										end
										undo_entry = true
									end
									if all.select { |e| !e.sarah_team? && !e.wet_worked? }.size < wet_needed
										wet_team = all.select { |e| !e.sarah_team } # all employees who are not on Sarah's Team
										wet_team_not_worked = wet_team.select { |e| !e.wet_worked? } # all employees who are not on Sarah's Team that have not worked Wet Station
										wet_team_not_worked.each do |e|
											e.update_attribute(:must_assign, 1)
											must_assign_wet.push(e)
										end
										wet_team.each do |e|
											e.update_attribute(:wet_worked, false)
										end
										undo_wet = true

app/views/locations/_employee.html.erb
<div class="locationEmployee">
	<%= link_to "#{employee.last_name}, #{employee.first_name}", employee %>
	<div class="locationEmployeeWorked">
		<p>
			Wet Station:
			<% if employee.wet_worked? %>
				Yes
			<% else %>
				No
			<% end %>
		</p>
		<p>
			Entry Station:
			<% if employee.entry_worked? %>
				Yes
			<% else %>
				No
			<% end %>
		</p>
		<p>
			Wet Ones:
			<% if employee.wones_worked? %>
				Yes
			<% else %>
				No
			<% end %>
		</p>
		<p>
			Rejects Station:
			<% if employee.qns_worked? %>
				Yes
			<% else %>
				No
			<% end %>
		</p>
		<p>
			Sarah's Station:
			<% if employee.sarah_worked? %>
				Yes
			<% else %>
				No
			<% end %>
		</p>
	</div>
</div>

app/views/locations/index.html.erb
<div class="pageHeader">
	<ul>
		<li><p>Primary Function</p></li>
		<li><%= link_to "Switch Locations", switch_locations_path, confirm: "Are you sure you want to switch locations?" %></li>
		<% if current_user.admin? %>
			<li><p>Do Not Touch</p></li>
			<li><%= link_to "New Location", new_location_path %></li>
			<li><%= link_to "Set Locations", set_locations_path, confirm: "Reset locations?" %></li>
			<li><%= link_to "Delete All Locations", delete_directions_path, confirm: "Click cancel now!" %></li>
		<% end %>
	</ul>
</div>
<div class="pageContent">
	<div class="lab">
		<p class="locationHeader">Lab: <%= pluralize(@lab.size, 'Employee') %></p>
		<div class="locationData">
			<p><%= @lab.map { |e| e.tier }.sum %> Tier Level Total</p>
			<p><%= @lab.size - @lab.map { |e| e.wet_worked }.count(false) %> Have Worked Wet Station</p>
			<p><%= @lab.size - @lab.map { |e| e.entry_worked }.count(false) %> Have Worked Entry Station</p>
			<p><%= @lab.size - @lab.map { |e| e.wones_worked }.count(false) %> Have Worked Wet Ones</p>
			<p><%= @lab.size - @lab.map { |e| e.qns_worked }.count(false) %> Have Worked Rejects Station</p>
			<p><%= @lab.size - @lab.map { |e| e.sarah_worked }.count(false) %> Have Worked Sarah's Station</p>
		</div>
		<div class="locationEmployees">
			<%= render partial: 'locations/employee', collection: @lab %>
		</div>
	</div>
	<div class="office">
		<p class="locationHeader">Office: <%= pluralize(@office.size, 'Employee') %></p>
		<div class="locationData">
			<p><%= @office.map { |e| e.tier }.sum %> Tier Level Total</p>
			<p><%= @office.size - @office.map { |e| e.wet_worked }.count(false) %> Have Worked Wet Station</p>
			<p><%= @office.size - @office.map { |e| e.entry_worked }.count(false) %> Have Worked Entry Station</p>
			<p><%= @office.size - @office.map { |e| e.wones_worked }.count(false) %> Have Worked Wet Ones</p>
			<p><%= @office.size - @office.map { |e| e.qns_worked }.count(false) %> Have Worked Rejects Station</p>
			<p><%= @office.size - @office.map { |e| e.sarah_worked }.count(false) %> Have Worked Sarah's Station</p>
		</div>
		<div class="locationEmployees">
			<%= render partial: 'locations/employee', collection: @office %>
		</div>
	</div>
	<div class="clear"></div>
</div>

app/views/locations/new.html.erb
<div class="employeeNew">
	<p class="employeeNewHeader">New Location</p>
	<div class="employeeNewForm">
		<%= form_for @location do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
			<div class="field">
				<p>Location Name</p>
				<%= f.text_field :name, autocomplete: "off" %>
			</div>
			<div class="action">
				<%= f.submit "Create" %>
				<%= link_to "Cancel", locations_path %>
			</div>
		<% end %>
	</div>
</div>